# Generated by Django 5.2.1 on 2025-06-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('preschool', 'PreSchool'), ('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('jhs', 'Junior High School'), ('management', 'Management')], default='lower_primary', help_text='Academic department or subject area', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('headmaster', 'Headmaster'), ('teacher', 'Teacher')], default='teacher', max_length=20),
        ),
    ]
