# Generated by Django 5.2.1 on 2025-06-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('preschool', 'PreSchool'), ('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('jhs', 'Junior High School'), ('management', 'Management')], default='lower_primary', max_length=50),
        ),
    ]
