# Generated by Django 5.2.1 on 2025-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
                ('date_of_lesson', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('lesson_number', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('strand', models.CharField(max_length=200)),
                ('sub_strand', models.CharField(max_length=200)),
                ('content_standard', models.TextField()),
                ('indicator', models.TextField()),
                ('performance_indicator', models.CharField(max_length=200)),
                ('core_competencies', models.TextField()),
                ('key_words', models.CharField(max_length=200)),
                ('starter', models.TextField()),
                ('starter_resources', models.TextField()),
                ('main', models.TextField()),
                ('main_resources', models.TextField()),
                ('plenary', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lesson Plans',
                'ordering': ['-date_created'],
            },
        ),
    ]
