# Generated by Django 5.2.1 on 2025-06-03 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0003_lessonplancheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplancheck',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplancheck',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('checked', 'Checked'), ('presented', 'Presented'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='lessonplancheck',
            unique_together={('lesson_plan', 'checked_by')},
        ),
    ]
