# Generated by Django 5.2.1 on 2025-06-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0004_lessonplancheck_notes_lessonplancheck_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplancheck',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rate the quality of this lesson plan', null=True),
        ),
    ]
