# Generated by Django 5.2.1 on 2025-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0005_lessonplancheck_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplancheck',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True),
        ),
    ]
